development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>    
  google_oauth2_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_oauth2_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_oauth2_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_oauth2_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>